title: up-for-grabs.net

exclude:
  - .github
  - assets
  - docs
  - licenses
  - node_modules
  - scripts
  - tests
  - .editorconfig
  - .eslintrc.json
  - .prettierrc.json
  - .rubocop.yml
  - .ruby-version
  - CNAME
  - Dockerfile
  - docker-compose.yml
  - Gemfile*
  - jest.config.js
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - tsconfig.json

github: [metadata]

# DO NOT DELETE THIS
# This is used to build up the array of projects rendered inside a <noscript>
# tag to support browsers which disable JS. For more context check out
# https://github.com/up-for-grabs/up-for-grabs.net/pull/1412 which explains what
# this gives us.
emptyArray: []

