---
name: ApplicationInsights-dotnet
desc: >-
  Azure Application Insights SDK for .NET. Includes public API surface, serialization and channel implementation
site: http://go.microsoft.com/fwlink/?LinkId=392727
tags:
- ".net"
- monitoring
- telemetry
- distributed-tracing
- application-insights
upforgrabs:
  name: up-for-grabs
  link: https://github.com/microsoft/ApplicationInsights-dotnet/labels/up-for-grabs
stats:
  issue-count: 6
  last-updated: '2019-10-26T06:41:47Z'
