---
name: ApplicationInsights-dotnet
desc: >-
  Azure Application Insights SDK for .NET. Includes public API surface, serialization and channel implementation
site: http://go.microsoft.com/fwlink/?LinkId=392727
tags:
- ".NET"
- Monitoring
- Telemetry
- Distributed tracing
- Application Insights
upforgrabs:
  name: up-for-grabs
  link: https://github.com/microsoft/ApplicationInsights-dotnet/labels/up-for-grabs
stats:
  issue-count: 7
  last-updated: '2019-09-24T23:01:02Z'
