name: FSharp.Configuration
desc: The FSharp.Configuration project contains type providers for the configuration of .NET projects.
site: https://github.com/fsprojects/FSharp.Configuration
tags:
- F#
- ".net"
- type provider
- YAML
- AppSettings
- ResX
upforgrabs:
  name: up-for-grabs
  link: https://github.com/fsprojects/FSharp.Configuration/labels/up-for-grabs
