---
name: FSharp.Configuration
desc: The FSharp.Configuration project contains type providers for the configuration of .NET projects.
site: https://github.com/fsprojects/FSharp.Configuration
tags:
- ".net"
- f#
- typeprovider
- yaml
- appsettings
- resx
upforgrabs:
  name: up-for-grabs
  link: https://github.com/fsprojects/FSharp.Configuration/labels/up-for-grabs
stats:
  issue-count: 1
  last-updated: '2019-10-23T14:06:20Z'
