---
name: LocalAppVeyor
desc: Run your AppVeyor builds, locally
site: https://github.com/joaope/localappveyor
tags:
- appveyor
- build
- console
- command-line
- c#
- ".net"
- ".net-core"
upforgrabs:
  name: up-for-grabs
  link: https://github.com/joaope/LocalAppVeyor/labels/up-for-grabs
stats:
  issue-count: 1
  last-updated: '2019-01-29T07:07:40Z'
  fork-count: 18
