---
name: TAG-Security
desc: >-
  CNCF Security Technical Advisory Group -- secure access, policy control, privacy, auditing, explainability
  and more!
site: https://www.cncf.io/projects/
tags:
- security
- cloud
upforgrabs:
  name: good first issue
  link: https://github.com/cncf/tag-security/labels/good%20first%20issue
stats:
  issue-count: 0
  fork-count: 417
