on:
  schedule:
  - cron: 0 18 * * 0
name: Cleanup stale projects
jobs:
  cleanupArchivedProjects:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cleanup archived projects
      uses: ./.github/actions/cleanup-archived-projects
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLY_CHANGES: 1
