name: JavaScript Checks

on:
  pull_request:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  cache: {}
  lint-and-test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Pull Request
        uses: actions/jest@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install # Assuming you're using npm for managing dependencies

      - name: Run Linter
        run: npm run lint # Adjust the command to run your linter

      - name: Run Tests
        run: npm test # Adjust the command to run your tests

