on:
  schedule:
    - cron: 0 14 * * *
  workflow_dispatch:
    inputs:
      apply-changes:
        description: 'Whether workflow should generate a pull request for these changes'
        required: false
        default: '1'

name: Update project stats
jobs:
  updateProjectStats:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@6bd3d993c602f6b675728ebaecb2b569ff86e99b
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0
      - name: Run script to update stats for all projects
        run: bundle exec ruby scripts/update_stats.rb
        env:
          GITHUB_TOKEN: ${{ secrets.SHIFTBOT_TOKEN }}
          APPLY_CHANGES: ${{ inputs.apply-changes }}
